store:
  availabilities:
    - German
    - International
  default_locale: en_GB
  localizations:
    - de_DE
    - en_GB
  categories:
    - Shopping Experiences    
  type: extension
  icon: store/extension-icon.png
  automatic_bugfix_version_compatibility: true
  tags:
    de:
      - Erlebniswelten
      - Erlebniswelten Sektion
      - Slider
      - Banner
      - Slide Builder
    en:
      - Shopping expierence
      - Shopping experience section
      - Slider
      - Banner
      - Slide Builder
  installation_manual:
    de: file:store/de/manual.md
    en: file:store/en/manual.md
  description:
    de: file:store/de/description.md
    en: file:store/en/descriptionmd
  highlights:
    de: 
      - file:store/de/highlight-1.md
      - file:store/de/highlight-2.md
      - file:store/de/highlight-3.md
      - file:store/de/highlight-4.md
    en: 
      - file:store/en/highlight-1.md
      - file:store/en/highlight-2.md
      - file:store/en/highlight-3.md
      - file:store/en/highlight-4.md
  features:
    de:
      - "🌐 Flexible, responsive Layouts mit der Elysium-Sektion für Erlebniswelten"
      - "🎛️ Slides mit umfangreichen Inhalts- und Darstellungsoptionen"
      - "🔍 SEO-Banner mit responsivem Layout: Überschrift, Beschreibung und Link individuell festlegbar – inkl. H-Element und HTML-Tags"
      - "🎥 Slide-Cover mit Videos, Bildern, Farben oder Farbverläufen möglich"
      - "🖼️ Bild-Banner gerätespezifisch anpassbar für Smartphone, Tablet und Desktop"
      - "🔗 Individuelle Slide-Verlinkung per Button oder vollflächig – mit relativen, absoluten URLs oder Sprungmarken"
      - "🛍️ Produkte mit Slides verknüpfen: Inhalte wie Bild, Name, Beschreibung und Link automatisch übernehmen oder manuell überschreiben"
      - "🧩 Eigene Slide-Templates per Twig-Datei erstellen – wiederverwendbar und anpassbar"
      - "➕ Slides über Zusatzfeld-Sets erweiterbar um eigene Inhalte wie Bilder oder Texte"
      - "🧱 Slides flexibel platzierbar in Slider- oder Banner-Elementen einer Erlebniswelt"
      - "⚙️ Slider-Element anpassbar: Autoplay, Navigation, Abstände und sichtbare Slides je Gerät frei definierbar"
      - "📐 Optimale Darstellung durch gerätespezifisch anpassbares Seitenverhältnis statt fixer Größen"
      - "🚀 Lighthouse-optimiert: Picture-Tag, Lazy Loading, Thumbnails und feste Seitenverhältnisse für Top-Performance und weniger Layout-Shifts"
    en:
      - "🌐 Flexible, responsive layouts with the Elysium section for Shopping Experience"
      - "🎛️ Slides with extensive content and display options"
      - "🔍 SEO banner with responsive layout: headline, description, and link individually configurable – including H-element and HTML tags"
      - "🎥 Slide cover with videos, images, colors, or gradients possible"
      - "🖼️ Image banner adaptable for smartphone, tablet, and desktop"
      - "🔗 Individual slide linking via button or full-surface – with relative, absolute URLs, or anchor links"
      - "🛍️ Link products with slides: automatically adopt content like image, name, description, and link or manually override"
      - "🧩 Create custom slide templates via Twig file – reusable and customizable"
      - "➕ Extend slides with additional field sets for custom content like images or text"
      - "🧱 Slides flexibly placeable in slider or banner elements of a Shopping Experience"
      - "⚙️ Slider element customizable: autoplay, navigation, spacing, and visible slides per device freely definable"
      - "📐 Optimal display through device-specific adjustable aspect ratio instead of fixed sizes"
      - "🚀 Lighthouse-optimized: picture tag, lazy loading, thumbnails, and fixed aspect ratios for top performance and fewer layout shifts"
  faq:
    de: 
      - question: Wie wird die kostenfreie Version der Elysium Erweiterung unterstützt
        answer: Diese kostenfreie Version der Elysium Erweiterung erhält nicht priorisierte Fehlerbehebungen und Kompatibilität Updates. Nur die aktuellste Major Version der Erweiterung, welche jeweils mit der aktuellsten Shopware Version kompatibel ist, erhält Updates. Außerdem wird kein Support garantiert und es wird keine Funktionserweiterungen geben.
    en: []