.build: 
  image: shopware/development:8.2-node-20.10-composer-2
  services:
    - name: mariadb:10.11 # spawn maria db
      alias: database
      entrypoint: [ "sh", "-c", "docker-entrypoint.sh $MYSQL_CMD" ]
  before_script:
    - mysql -uroot -papp -hdatabase -e 'CREATE database `app`' # create database `app` for shopware
    - cd /app && composer create-project shopware/production:v6.6.8.0 . # create shopware project under /app dir
    - composer require --dev phpstan/phpstan # add phpstan
    - cp $CI_PROJECT_DIR/.devops/phpstan.neon . # copy phpstan config to shopware app
    - cp $CI_PROJECT_DIR/.devops/.env.local . # copy ci specific .env to shopware app
    - bin/console system:install --basic-setup -q -n # install shopware app
    - cp -r $CI_PROJECT_DIR custom/static-plugins/. && composer require blurcreative/elysium-slider # copy plugin files and require